POST http://localhost:3001/api/users/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVoc1VndzUyang5VCIsIm5hbWUiOiJhIiwiaWF0IjoxNjIwNjEyMzI2fQ.6fuBLtVIBsjWTsfqstmtBWvTOWiJJrx2zNvV1WRkNf4

{
    "id": "@tem",
    "name": "a",
    "password": "weakpassword"
}